### ISSUE TITLE
poppy_4dof or poppy_dof4

### ISSUE THREAD

**Issue by jjehl** [poppy-project/poppy-ergo-starter#2]
For the software the module can not be named poppy_4dof... because the function camelcase_to_underscore(name) in poppy.creature.abstractcreature.py return a module named poppy4dof_arm_mini althought it should be poppy_4dof_arm_mini.

def camelcase_to_underscore(name):
    s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
    return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).lower()

I don't see a simple solution, just avoid to use number just after underscore in the name of the creature.

**Comment by show0k** [comment]
Ye, that's true, it's a bug inside poppy-creature.
This fix the issue I think.

```
def camelcase_to_underscore(name):
    return re.sub('([a-z0-9])([A-Z0-9])', r'\1_\2', name).lower()
```

 But "PoppyDof4ArmMini" should be named Poppy4DofArmMini. You did it to avoid the camelcase_to_underscore bug @jgrizou ?

**Comment by jgrizou** [comment]
I have not written a line on the software side ^^ but I agree Poppy4DofArmMini would be more consistent.

**Comment by jjehl** [comment]
I have changed the name of the creature to avoid the bug. With your fix the name Poppy_4dof will work for sure but you will have another problem...
A creature name poppy2-ergo won't respect the convention because the module will be poppy_2_ergo and it should be poppy2_ergo.
I guess the problem can not be solved because the convention with the case can't work with number (not lower and upper case) ?

Anyway your fix work with poppy-4dof, so it is OK for now.
